services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Leuchtfeuer\Auth0\:
    resource: '../Classes/*'

  Leuchtfeuer\Auth0\Domain\Repository\ApplicationRepository:
    public: true

  Leuchtfeuer\Auth0\Domain\Repository\UserRepositoryFactory:
    public: true

  Leuchtfeuer\Auth0\Service\AuthenticationService:
    public: true
