name: CI
on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - master

jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.2, 7.3, 7.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: php-cs-fixer:2.17.1
      - name: Check PHP CS
        run: php-cs-fixer fix --config .php_cs --using-cache false --show-progress dots -vvv

  phpunit:
    needs: integration
    name: PHP ${{ matrix.php-version }} - T3 ${{ matrix.typo3-version }}
    runs-on: ubuntu-18.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        experimental: [false]
        php-version: [7.2, 7.3, 7.4]
        typo3-version: [^9.5, ^10.4]
        include:
          - php-version: 7.4
            typo3-version: 9.5.x-dev
            experimental: true

          - php-version: 7.4
            typo3-version: 10.4.x-dev
            experimental: true

          - php-version: 7.4
            typo3-version: ^11.0
            experimental: false

          - php-version: 7.4
            typo3-version: dev-master
            experimental: true
    env:
      PHP_VERSION: ${{ matrix.php-version }}
      TYPO3_VERSION: ${{ matrix.typo3-version }}

    steps:
      - name: Output Environment Data
        run: |
          echo "Running tests with TYPO3 ${TYPO3_VERSION} and PHP ${PHP_VERSION}"

      - name: Checkout
        uses: actions/checkout@v2

      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '5.7'
          root-password: $3cret

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: fileinfo, gd, zip, zlib, openssl, intl, PDO, json, pcre, session, xml, filter, hash, mbstring, SPL, standard, mysqli
          ini-values: max_execution_time=240,memory_limit=256M
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        env:
          PHP_VERSION: ${{ matrix.php-version }}
          TYPO3_VERSION: ${{ matrix.typo3-version }}
        run: |
          ./Build/install.sh
          export TYPO3_PATH_WEB=$PWD/.Build/web

      - name: Run PHP Unit
        run: |
          .Build/bin/phpunit --colors --configuration Tests/Build/FunctionalTests.xml Tests/Functional --bootstrap .Build/vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTestsBootstrap.php --coverage-clover=coverage.xml

          if [[ "${{ matrix.php-version }}" == "7.4" ]] && [[ "${{ matrix.typo3-version }}" == "^10.4"  ]]; then
            bash <(curl -s https://codecov.io/bash)
          fi
